# Generated by Django 2.1.1 on 2018-10-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainModel',
        ),
    ]
