# Generated by Django 2.1.2 on 2018-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
