# Generated by Django 2.1.2 on 2018-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_resultmodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='px',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='py',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
